### ISSUE TITLE
CSS Styling Issue?

### ISSUE THREAD

**Issue by Brad-Le** [louislam/vestacp-crossover-adminlte#1]
I realize this theme is incomplete, but something as big as http://i.imgur.com/59mYk29.png should be fixed soon?

**Comment by Brad-Le** [comment]
http://i.imgur.com/2vAMRVa.png

**Comment by louislam** [comment]
Some pages are not working like this, because I have not applied the style to these pages yet. So that why you should not use in production servers. I will finish these pages later.

I am sorry that the progress is slow now, because I am quite busy these days.

**Comment by Brad-Le** [comment]
No problem.  I am not using this in production, just seeing my options.  I just think something like this is quite major and should be addressed soon.

**Comment by phillw** [comment]
Hi,
Have also noticed this issue.
Would be nice to see it fixed since it is the first page a user see's :-)

Best theme for VestaCP!

Best Regards,

**Comment by Jarrrk** [comment]
Hi,

If you can't finish this I'll gladly fork it and fully release it.

Cheers

**Comment by louislam** [comment]
You are welcome, sorry I am really too busy :(

**Comment by phillw** [comment]
@Jarrrk 
That would be fantastic. I am able and have time to help, if you like.

**Comment by joubertredrat** [comment]
+1
Amazing this theme
