### ISSUE TITLE
Anything on the left tab

### ISSUE THREAD

**Issue by LordApo** [louislam/vestacp-crossover-adminlte#4]
![screenshot_1](https://cloud.githubusercontent.com/assets/17224437/15987636/458ddce0-302f-11e6-9db7-0e7dd2939d21.png)

**Comment by louislam** [comment]
Are you using the latest version of VestaCP?

**Comment by LordApo** [comment]
Yes

**Comment by louislam** [comment]
I cannot re-produce the problem. Could you please press "Ctrl + U" in the page and send me the html code to me via Email?

**Comment by LordApo** [comment]
It's working after a fresh install of the system, thanks.
