### ISSUE TITLE
it gives me blank page

### ISSUE THREAD

**Issue by Dj-jom2x** [louislam/vestacp-crossover-adminlte#6]
it gives me blank page with bluish bg .. i copy them all .. only login has design

**Comment by louislam** [comment]
Did you install the VestaCP recently? I found out that VestaCP developer actually breaks the original theme itself recently. I will try to follow, at this stage, please rollback first.

related issue: https://github.com/serghey-rodin/vesta/issues/745

**Comment by Dj-jom2x** [comment]
how to roll back xD

**Comment by Dj-jom2x** [comment]
i dont install vestacp before

**Comment by saverioz** [comment]
@louislam Same problem for me please fix this soon, this is the best theme ever :P

**Comment by saverioz** [comment]
@louislam bump?

**Comment by saverioz** [comment]
@louislam I would be great if you can upload all web folder of the version 0.9.8 (Release: 15), simple and efficent so we can use your theme, on the net this version does not exist.

**Comment by louislam** [comment]
Good idea.

Here it is. 
http://file.app.louislam.net/web.tar.gz

**Comment by saverioz** [comment]
Thank you @louislam :) TOP

**Comment by saverioz** [comment]
It works ;) you can close Issue

**Comment by Dj-jom2x** [comment]
dint try yet but thanks saverioz said it works so i will believe him

**Comment by Dj-jom2x** [comment]
i think you forgot the filemanager ... or im blind XD

**Comment by arthurcvm** [comment]
This archives solve the blank problem in my VestaCP also. The conventional installation in "Readme" (2 methods) no function.
