### ISSUE TITLE
BUG: FTP account not collapsing on new Web Domain

### ISSUE THREAD

**Issue by drosendo** [louislam/vestacp-crossover-adminlte#8]
Hi,

When adding new Web Domain, and ticking the " Additional FTP" option, nothing happens.
After save, the  "Additional FTP" shows the input boxes, but the "Username" input is disabled.

**Comment by drosendo** [comment]
Any feedback? or confirmation?

**Comment by louislam** [comment]
Confirmed, it is a bug causes by the theme.

**Comment by louislam** [comment]
Just released v1.3, this version should fixed the problem.

**Comment by drosendo** [comment]
I will have a try.

THanks,
David
